### ISSUE TITLE
Feature request: Omit types in typescript files

### ISSUE THREAD

**Issue by thany** [Nyphet/jsdoc-generator#4]
**Is your feature request related to a problem? Please describe.**
In Typescript, types are defined in code. Defining them again in jsdoc, may lead to inconsistenties when changing type in code, and forgetting to also update the jsdoc. Moreover, they are superfluous, as the editor doesn't need jsdoc to display types for intellisense popups.

**Describe the solution you'd like**
An option to enable adding types to generated jsdoc in `.ts` and `.tsx` files.

So that if a developer needs them, for example to generate separate documentation using a generator tool. I feel this option should be set to disabled by default, as adding types in jsdoc in typescript is technically superfluous.

**Describe alternatives you've considered**
N/A

**Environment used**
Typescript version: 4.9.3
VSC versione: 1.74.1
OS: Windows 10

**Comment by Nyphet** [comment]
As of now this extension only works for Typescript, it's not even triggered for Javascript files. This is because it uses the Typescript node parser to infer types, which is not available for Javascript files.  
An option to not generate types within the JSDoc is already there: do not use this extension and use only the base feature from VSCode.

I hope this resolves your issue, if it doesn't do not hesitate to reopen this issue. Thanks for using my extension!

**Comment by thany** [comment]
Since when does VScode have this functionality built-in? And do you know how to trigger it? Because it surely doesn't when I type `/**` above a function.

PS: I can't reopen issues 😉

**Comment by Nyphet** [comment]
I'm attaching here a couple of videos showing off the base feature from VSCode.

https://user-images.githubusercontent.com/65339023/209017463-dac6c3aa-eb82-4fa5-a494-d295ffa0e0cd.mp4

https://user-images.githubusercontent.com/65339023/209017471-667777b1-b180-47a7-b0fd-c98a921ec1c0.mp4

**Comment by thany** [comment]
Doesn't work for me at all. It does absolutely nothing. Maybe it's another plugin that's adding jsdoc for you. Even with all extensions disabled, this is not working. I've honestly never even heard of vscode bing capable of this. The [documentation](https://code.visualstudio.com/Search?q=jsdoc) doesn't seem to list anything relevant, and [I also can't find](https://github.com/microsoft/vscode/issues?q=is%3Aissue+jsdoc+generate+is%3Aclosed) anything pertaining to generating jsdoc. What vscode *can* do, is provide assistance in *editing* jsdoc, but not in generating it.

This is probably why I reached out to this addon in the first place...

**Comment by Nyphet** [comment]
Please, have a look at [this](https://code.visualstudio.com/docs/languages/javascript#_jsdoc-support).  
In particular, that section says:

> Quickly create JSDoc comments for functions by typing /** before the function declaration, and select the JSDoc comment snippet suggestion

Maybe, by accident, you disabled automatic JSDoc generation.  
Check if in your VSCode settings you have the following line: `"javascript.suggest.completeJSDocs": false`  
If so, set it to true. If not, the issue should be moved to VSCode itself.

Anyway, as you said, the main reason for my extension is to generate documentation with external tools. I'll tell you more, I created this extension exactly because at the place I work there wasn't any standardized tool to generate JSDoc to use for documentation generation for our codebase. After, I decided to make it available for free to anyone who may need it.

Furthermore, having JSDoc with types allows other 3 useful things:  
1. Having all the relevant types in the comment before the function, allowing clearer and faster understanding of each parameter and the return value.
2. Help with regressions. Combined with other extensions that detect when JSDoc types don't match with the actual types, it can help to check if and why a function, or interface, changed types.
3. To explicitly define types that in the code may be not correctly inferred.

I hope this solves your issue, if you need further help or have more questions don't hesitate to comment again.

**Comment by imsergiobernal** [comment]
I would like to have this as well! VSC snippet generator does not have (or I didn't found) author and timestamp data, which are the things I like from this extension. I have to remove type every time I write some commentdoc

**Comment by Nyphet** [comment]
Since more than one person wants this feature, I will add it along with support for JavaScript files.

**Comment by Nyphet** [comment]
Added with version v1.2.0
